<?php

//  Implements hook_permission
function form_example_permission() {
    return array(
        'submit form_example' => array(
            'title' => t('Submit form_example'),
            'description' => t('Submit the form_example form'),
        ),
        'access form_example submissions' => array(
            'title' => t('Submit form_example submissions'),
            'description' => t('Access the form_example submissions'),
        ),
    );
}

//  Implements hook_menu
function form_example_menu() {
    $items = array();
    $items['form-example'] = array(
        'title' => 'Contacto con Toyota',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_example_form'),
        'access arguments' => array('submit form_example'),

    );
    $items['form-submissions'] = array(
        'title' => 'My Form Submissions',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'form_example_submissions',
        'access arguments' => array('access form_example submissions'),

    );

    return $items;
}

//  Example Form
function form_example_form($form,&$form_state) {
    $form['mynumber'] = array(
        '#type' => 'textfield',
        '#title' => t('Cédula'),
        '#size' => 70,
        '#maxlength' => 10,
        '#minlength' => 9,
        '#required' => TRUE,
        '#description' => t('Identificación Nacional Únicamente'),
    );

    $form['mytextfield'] = array(
        '#type' => 'textfield',
        '#title' => t('Asunto'),
        '#size' => 70,
        '#maxlength' => 128,
        '#required' => TRUE,
    );

    $form['mytext'] = array(
        '#type' => 'textarea',
        '#title' => t('Descripción'),
        '#description' => t('Razón del contacto con la empresa'),
        '#required' => TRUE,
        '#default_value' => '',
        '#size' => 70,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Enviar'),
    );

    return $form;
}

//  Validation handler
function form_example_form_validate($form, &$form_state) {
    if (!is_numeric($form_state['values']['mynumber'])) {
        form_set_error('mynumber', t('Ingrese una Cédula Válida'));
        return FALSE;
    }

    return TRUE;
}

//  Submit handler
function form_example_form_submit($form, &$form_state) {
    $fe_id = db_insert('form_example') -> fields(array(
        'mynumber' => $form_state['values']['mynumber'],
        'mytextfield' => $form_state['values']['mytextfield'],
        'mytext' => $form_state['values']['mytext'],
    )) -> execute();
    drupal_set_message(t('Formulario Enviado Correctamente.'));
}

//  View the form submissions
function form_example_submissions() {

    $query = db_select('form_example', 'fe');
    $query 
    -> fields('fe', array('fe_id', 'mynumber', 'mytextfield', 'mytext'))
    -> range(0, 50)
    -> orderBy('fe.fe_id');

    $results = $query  ->  execute();

    $header = array(t('ID'), t('Cédula'), t('Asunto'), t('Descripción'));

    $rows = array();

    foreach ($results AS $result) {
        $rows[] = array(
            check_plain($result -> fe_id),
            check_plain($result -> mynumber),
            check_plain($result -> mytextfield),
            check_plain($result -> mytext),
        );
    }

    return theme('table', array('header' => $header, 'rows' => $rows));
}
